---
development:
  cloud_name: hbkxssffq
  api_key: '193563743245418'
  api_secret: 6piZGZARIdVJAfNxCbYzaIq3xSE
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hbkxssffq
  api_key: '193563743245418'
  api_secret: 6piZGZARIdVJAfNxCbYzaIq3xSE
  enhance_image_tag: true
  static_image_support: true
  secure: true
test:
  cloud_name: hbkxssffq
  api_key: '193563743245418'
  api_secret: 6piZGZARIdVJAfNxCbYzaIq3xSE
  enhance_image_tag: true
  static_image_support: false
